### ISSUE TITLE
ERR-1002 Unable to find item ID for item

### ISSUE THREAD

**Issue by ghost** [rafael-trevisan/apex-plugin-ig_simple_checkbox#1]
Hello, sorry i'm testing this plugin and find a error with submit page button, i have this error 
ERR-1002 Unable to find item ID for item "C51058629785297626906" in application "140804".
You can see example and error description on   https://apex.oracle.com/pls/apex/f?p=140804:1
Help me.

**Comment by rafael-trevisan** [comment]
Hey @jfernal, thanks for reporting it.

I'll take a look at it.

**Comment by rafael-trevisan** [comment]
Hey @jfernal, this issue has been fixed in the [v18.2.1](https://github.com/rafael-trevisan/apex-plugin-ig_simple_checkbox/releases/tag/v18.2.1)

Cheers 👍
