### ISSUE TITLE
Not keyboard enabled

### ISSUE THREAD

**Issue by jrdad1** [rafael-trevisan/apex-plugin-ig_simple_checkbox#2]
I cannot check this field by pressing the spacebar to check it (and to uncheck it). Can this be implemented?

**Comment by rafael-trevisan** [comment]
Hey @jrdad1, here you go. Your suggestion has been implemented in [v18.2.2](https://github.com/rafael-trevisan/apex-plugin-ig_simple_checkbox/releases/tag/v18.2.2)

Cheers 👍
