### ISSUE TITLE
After Page Load first time not cheked

### ISSUE THREAD

**Issue by NivethaRamanth** [rafael-trevisan/apex-plugin-ig_simple_checkbox#5]
After the report is loaded, if you click the checkbox it will not be selected/unselected.  Only after 4 to 5 clicks it can be edited.

**Comment by rafael-trevisan** [comment]
Hey @NivethaRamanth,

I guess [this](https://github.com/rafael-trevisan/apex-plugin-ig_simple_checkbox/issues/4#issuecomment-369960895) helped you.

Let us know if you still have any issue reopening this issue, ok?

**Comment by NivethaRamanth** [comment]
Its working fine Thanks
