### ISSUE TITLE
Checked values not shown

### ISSUE THREAD

**Issue by jeffreykemp** [rafael-trevisan/apex-plugin-ig_simple_checkbox#6]
Regardless of whether the value of the column is Y or N, no check mark is shown, in display or edit mode.

APEX 5.1.4

**Comment by rafael-trevisan** [comment]
Hmm, by default IG Simple Checkbox has 0/1 for unchecked/checked value respectively... so, I’m sorry if these questions seem silly but they will help to picture better your scenario before asking the famous “could you mimic your problem at apex.oracle.com?”

1. Are you using the same setting of values for the plugin and for your column?

2. Do you have only one occurrence of this column in your query? I’ve seen a similar problem when user query the column twice, once for the plugin and “another” just to check.

3. Are you using a custom theme? IG Simple Checkbox relies on Univeral Theme to “render” the funny check mark.

4. Have any error on console? Like 404 for IG Simple Checkbox css or js?

5. Any other details you think might help enlighten your issue.

Cheers

**Comment by rafael-trevisan** [comment]
Forgot another important point: which browser are you using? There's a specific version for IE. If you search here is the issues you can find out more about.

**Comment by jeffreykemp** [comment]
1. I've tried "Y" and null, and "Y" and "N" with the same effect.
2. Only the one occurrence
3. Using Universal Theme unmodified out of the box
4. No errors
5. Can't think of any, sorry.

Browser is Chrome 64.0.3282.186

p.s. if this same plugin doesn't work in IE this will be a problem as we need to support all the common browsers including IE, Chrome, Firefox and Safari.

**Comment by rafael-trevisan** [comment]
IG Simple Checkbox with support for IE (besides all other browsers) is working fine and is here => https://github.com/rafael-trevisan/apex-plugin-ig_simple_checkbox/releases/download/v18.2.3/IG-Simple-Checkbox-APEX-Plugin_IE11.zip

I just need to find a free time here to work on a single and final version and merge it into the master.

Well, in this case, I can't see another option other than asking to mimic the problem on apex.oracle.com (or wherever you prefer) and send me the link (eventually credentials to log in as a developer as well) so I could take a look and see what's going on.

If you don't feel comfortable sharing the link and/or temp credentials here, feel free to DM me on twitter at [@tr3v15](https://twitter.com/tr3v15) or fire me an email at rafael [at] trevis [dot] ca

**Comment by NivethaRamanth** [comment]
Hi,
I got the same issue, as a temporary fix Iam using the below code in page Inline CSS

.ig-simple-checkbox.checkbox_group input+label::after
{
background-color: rgba(0,0,0,.2) !important;
}

**Comment by rafael-trevisan** [comment]
Hi @NivethaRamanth,

Your workaround means that or you're using IG Simple Checkbox on APEX 5.0 or you've migrated your app from 5.o to 5.1 and your Universal Theme files are still the old ones.

Please check which "version" of Universal Theme you're using in your app and make sure you are on **1.1** 

![update_universal_theme_files](https://user-images.githubusercontent.com/17282530/37104552-de2eb9d8-21e1-11e8-89ad-4e090f8f382d.png)

**Comment by NivethaRamanth** [comment]
Hi Rafael,
Thanks.
I just checked the Universal theme version, yes its the old one 42/1.0
So the issue is because of this old version? what is the impact if I modify to new one?

**Comment by jeffreykemp** [comment]
Upgrading to UT 1.1 *might* cause customisations you've made to not work the same way, so some testing will be required. Take a backup of your application prior to upgrading it.

Tip: don't do what I did (create a new application, export theme, import theme, switch theme). That was the hard way! The way to upgrade is very simple:

https://apex.oracle.com/pls/apex/f?p=42:1909:::NO:::

**Comment by NivethaRamanth** [comment]
Hi Jeffrey,
Thank you, I will take a backup and upgrade.
